### ISSUE TITLE
OSError: SavedModel file does not exist at: .../modello.h5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by grgfede** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#15]
Hello everybody.
When I perform the detection of the model (previously converted), the process fails.

This is the error:
`Using TensorFlow backend.
2021-07-15 18:43:29.906946: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-07-15 18:43:29.928893: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2021-07-15 18:43:29.929625: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5651561b9640 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-07-15 18:43:29.929641: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-07-15 18:43:29.931405: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-07-15 18:43:29.998557: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 18:43:29.998852: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5651561602b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-07-15 18:43:29.998868: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1050 Ti with Max-Q Design, Compute Capability 6.1
2021-07-15 18:43:29.999002: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 18:43:29.999195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce GTX 1050 Ti with Max-Q Design major: 6 minor: 1 memoryClockRate(GHz): 1.4175
pciBusID: 0000:01:00.0
2021-07-15 18:43:29.999315: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2021-07-15 18:43:29.999376: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2021-07-15 18:43:29.999429: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2021-07-15 18:43:29.999478: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2021-07-15 18:43:29.999529: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2021-07-15 18:43:29.999579: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2021-07-15 18:43:30.002640: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-07-15 18:43:30.002658: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-07-15 18:43:30.002694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-15 18:43:30.002701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-07-15 18:43:30.002706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
Traceback (most recent call last):
  File "people_detection_image.py", line 23, in <module>
    model = models.load_model(model_path, backbone_name='resnet50')
  File "/home/federico/Scrivania/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-/keras_retinanet/models/__init__.py", line 87, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "/home/federico/miniconda3/envs/retina/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/home/federico/miniconda3/envs/retina/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-/model.h5/{saved_model.pbtxt|saved_model.pb}`

Can anyone help me?

**Comment by Samjith888** [comment]
The file is not exist in the below path

`Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-/model.h5/`
